apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.env.jwtSecret | b64enc | quote }}
