server:
  port: ${PORT:8080}
  error:
    include-message: always
spring:
  application:
    name: payments
  thymeleaf:
    cache: false
orders:
  service:
    url: ${ORDERS_SERVICE_URL:http://orders:8080}
    admin-user: ${ORDERS_SERVICE_USER:payments-service}
frontend:
  url: ${FRONTEND_URL:http://localhost}
