{{- $root := . -}}
{{- range $name, $db := .Values.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "kursach.dbSecretName" (dict "Root" $root "Name" $name)) $db.secretName }}
  labels:
    {{- include "kursach.labels" $root | nindent 4 }}
type: Opaque
data:
  username: {{ $db.username | b64enc | quote }}
  password: {{ $db.password | b64enc | quote }}
  database: {{ $db.database | b64enc | quote }}
  postgres-password: {{ ($db.superuserPassword | default $db.password) | b64enc | quote }}
{{- if $db.replicationPassword }}
  replication-password: {{ $db.replicationPassword | b64enc | quote }}
{{- end }}
---
{{- end }}

{{- if and .Values.redis.enabled .Values.redis.auth.enabled .Values.redis.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "kursach.redisSecretName" .) .Values.redis.auth.existingSecret }}
  labels:
    {{- include "kursach.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey | default "redis-password" }}: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
