{{- if .Values.auth.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db
type: Opaque
stringData:
  username: "{{ .Values.auth.database.username }}"
  password: "{{ .Values.auth.database.password }}"
{{- end }}
{{- if .Values.orders.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
type: Opaque
stringData:
  username: "{{ .Values.orders.database.username }}"
  password: "{{ .Values.orders.database.password }}"
{{- end }}
{{- if .Values.chat.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-db
type: Opaque
stringData:
  username: "{{ .Values.chat.database.username }}"
  password: "{{ .Values.chat.database.password }}"
{{- end }}
