apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat.fullname" . }}
  labels:
    app: {{ include "chat.name" . }}
    chart: {{ include "chat.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chat.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chat.name" . }}
    spec:
      containers:
        - name: chat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: KAFKA_BROKERS
              value: {{ .Values.env.KAFKA_BROKERS | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
