apiVersion: v2
name: delivery
version: 0.1.0
description: Umbrella chart for delivery microservices (Auth, Orders, Chat, BFF, Frontend) with Kafka and Postgres dependencies.
type: application
dependencies:
  - name: kafka
    version: 26.9.3
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
    alias: auth-postgres
    condition: auth.postgresql.enabled
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
    alias: orders-postgres
    condition: orders.postgresql.enabled
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
    alias: chat-postgres
    condition: chat.postgresql.enabled
